#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/captureToGif.jar:$APPDIR/lib/core.jar:$APPDIR/lib/ScreenCapturer.jar:$APPDIR/lib/gifAnimation.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl.jar:$APPDIR/lib/opengl.jar" captureToGif
